### ISSUE TITLE
앱 첫 시작화면(LoadActivity)에서 tts 미작동

### ISSUE THREAD

**Issue by Eiwon** [Kanteloper/avatar_android_app#7]
## 문제 
다른 activity에서 LoadActivity로 이동하면 tts가 작동하지만, 앱 첫 실행시 나오는 LoadActivity에서는 작동하지 않음

## 의견
LoadActivity 전에 시간지나면 넘어가는 로딩화면을 추가로 넣어야 할 듯

**Comment by Kanteloper** [comment]
## 해결
TextToSpeech 클래스에서 OnInitListener 메소드 안에 speak 함수를 호출해야 tts engine이 바운딩 되어
작동한다.

**Comment by Kanteloper** [comment]
LoadActivity 자체가 로딩화면 임. 따로 추가할 필요 없음.

**Comment by Kanteloper** [comment]
싱글톤 패턴을 수정함으로써 해결
